# DB Config
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.tfwdeccxlkznfyqzwtns&password=${db_password}

# Hibernate config
spring.jpa.hibernate.ddl-auto=update